### ISSUE TITLE
How to create a phar file from local composer path?

### ISSUE THREAD

**Issue by avshidid** [clue/phar-composer#102]
I have created my composer package on my local machine ( windows ) but not able to convert it to the phar file,

I am trying to use following command,

php phar-composer.phar build -v C:/composer-package-builder

Also tried with the private git path but unable to execute there as well.

In short I my environment is private so I use "respositories" to load the composer packages. How should I create phar files for such packages?

**Comment by clue** [comment]
@avshidid What problem are you seeing exactly?

The command looks fine to me. Have you tried changing into this directory and then running this project without any path arguments?

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:
