### ISSUE TITLE
Composer 2 compatibility

### ISSUE THREAD

**Issue by gabesullice** [clue/phar-composer#106]
I encountered an error similar to #105 and I believe that the error is related to [the breaking changes made by Composer 2](https://getcomposer.org/upgrade/UPGRADE-2.0.md).

Specifically:

> * `vendor/composer/installed.json` format changed:
>   * packages are now wrapped into a "packages" top level key instead of the whole file being the package array
>   * packages now contain an "installed-path" key which lists where they were installed
>   * there is a top level "dev" key which stores whether dev requirements were installed or not

**Comment by nargotik** [comment]
I have maded one line pull request to solve this issue and continue to have backward to composer 1.

**Comment by knnnrd** [comment]
I also bumped into this issue. What's the reason that the PR isn't accepted yet?

**Comment by clue** [comment]
@gabesullice Thanks for reporting, this indeed didn't work with Composer 2.0 due to the referenced change in Composer itself. I've just fixed this via #114. :shipit:
