### ISSUE TITLE
Deterministic, reproducible builds?

### ISSUE THREAD

**Issue by wimleers** [clue/phar-composer#110]
We've successfully used `clue/phar-composer` in a small (closed source) PHP library. Thank you so much for this awesome tool! 👏 🙏 🥳 

That being said, we've really struggled in figuring out what is causing it to generate a different binary every time, even when keeping everything identical.

https://bugs.php.net/bug.php?id=77229&edit=1 pointed me to this probably being a problem with `phar` itself. But not even using the same approach as `composer` uses with https://github.com/Seldaek/phar-utils appears to work.

What am I missing? 🤓 

_See https://reproducible-builds.org/_

**Comment by clue** [comment]
@wimleers Thanks for reporting, I too am a big fan of reproducible builds :+1: 

Have you checked how exactly the archives differ? Might be some timestamps or possibly some duplicate contents (#100). If anybody wants to pick this up, I'm happy to accept PRs! :shipit: 

As much as I'd love to work on this myself, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently). If you need this for a commercial project and you want to help sponsor this feature, feel free to reach out and I'm happy to take a look.

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. If you feel this is still relevant, please come back with more details and we can always reopen this :+1:
