### ISSUE TITLE
Excluding files with gitattributes

### ISSUE THREAD

**Issue by pejman-hkh** [clue/phar-composer#133]
I think git attributes for ignore some folders (export-ignore) in phar file should add.

**Comment by SimonFrings** [comment]
Hey @pejman-hkh, there's already a ticket open for this where we're discussing different approaches to exclude files, see #5.

We're already using Symfony's Finder component which could interpret the `.gitattributes` file, so you could also manually filter this until this is supported OOTB. If you have any ideas or suggestions on how to approach this feature, we're happy to hear about them in #5.

I believe this should answer your question, so I will close this ticket for now :+1:
