### ISSUE TITLE
validate composer.json

### ISSUE THREAD

**Issue by staabm** [clue/phar-composer#43]
phar-composer commands assume the composer.json provided is valid.

In case it is not valid it sometimes produces strange things, e.g. name a project "myproject" (without a vendor prefix, which of course is invalid).
-> it will create a "yproject.phar" (without the leading "m"). It took some time to find out, that this problems are caused by my invalid composer.json.

phar-composer could do a better job and do a `composer validate` before each runs its own commands. In case of errors, skip its own command and print the error.

**Comment by clue** [comment]
Interesting suggestion :-)

Right now, this project does not necessarily depend on composer at all. You can use this tool to bundle a local project directory without requiring composer.

I considered embedding composer (#11), in which case it certainly makes sense to also add a validation step.

What are your thoughts?

**Comment by staabm** [comment]
Not sure how much dev-time it would take to embbed composer and how big the resulting phar-composer will be. This 2 parameters would be the actual drivers IMO.

If this issue is the only reason for embedding composer we could also just use `composer validate` in case `composer` is available (which is very likely as you already mentioned in the referenced ticket).

**Comment by clue** [comment]
> we could also just use `composer validate` in case `composer` is available

Sounds like a sane approach (sufficiently easy to implement independently of #11). Would you care to file a PR? :)

**Comment by staabm** [comment]
Will PR tomorrow

**Comment by kasperg** [comment]
An alternate approach would be to use [`justinrainbow/json-schema`](https://github.com/justinrainbow/json-schema) and [the schema for `composer.json`](https://github.com/composer/composer/blob/master/res/composer-schema.json).

**Comment by clue** [comment]
@staabm Thank you for the suggestion, I understand where you're coming from, but I'm having to close this as out of scope as per #88

Please report back and/or open a new PR if you feel this is still needed and we can reconsider this :+1:
