### ISSUE TITLE
Status on the project?

### ISSUE THREAD

**Issue by ppetermann** [clue/phar-composer#46]
Is this still maintained or was this abandoned?  

theres pull requests open since last year, a lot of issues never touched, no releases after the last commits (and those quite a while ago)..

**Comment by clue** [comment]
Thanks for poking me, I've certainly been slacking behind :-)

So **yes**, this project is alive and still maintained!

Any input is welcome! If you happen to find an uncommented ticket, please free free to comment :-) Also, please let me know if anything has still gone unnoticed.

I'll leave this ticket open as a reminder to tag a new release… :shipit:

**Comment by ppetermann** [comment]
so, how did that work out ;)

**Comment by clue** [comment]
> so, how did that work out ;)

[v1.0.0 just released](https://github.com/clue/phar-composer/releases/tag/v1.0.0) :shipit: :+1: 

> Any input is welcome! If you happen to find an uncommented ticket, please free free to comment :-) Also, please let me know if anything has still gone unnoticed.

So, how did that work out? :grinning:
