### ISSUE TITLE
Use --no-dev When Building

### ISSUE THREAD

**Issue by mcordingley** [clue/phar-composer#52]
I just ran this on one of my own libraries to see how it would work (neat, btw!) and found that it pulled in development dependencies into the generated phar. It would be nice to have an option to leave off dev dependencies from the built phar file. It would be nicer still to (eventually) have that be the default and there be an option to explicitly include dev dependencies.

**Comment by mcordingley** [comment]
This would help keep the size of generated phar files down, as dev dependencies can be quite large at times. My own small library that I did a test build of this on created a phar four megabytes large. While it has some dependencies of its own, most of that is the dev deps.

**Comment by mcordingley** [comment]
Looks like #37 does this. :+1:

**Comment by clue** [comment]
As a temporary workaround, you may also try to install your library with `composer install --no-dev` and then running phar-composer.
