### ISSUE TITLE
Build Libraries?

### ISSUE THREAD

**Issue by mcordingley** [clue/phar-composer#53]
It looks like this project is meant to build an executable phar version of a project, like the Boris REPL. Can it also be used to build includable libraries?

It would be neat to be able to build a non-executable phar, with dependencies, for some given library and then be able to include that into a small or legacy project. The only rub I see is if multiple libraries are included this way that have overlapping dependency trees.

**Comment by clue** [comment]
This is an excellent question and I agree that it would be nice to support this :+1: 

This project currently focuses on the `bin` configuration in your `composer.json`, which is commonly not set for library projects. FWIW, ticket #29 discusses adding an explicit CLI option to pass this.

Has anybody already looked into using phar-composer for library projects? Any input/feedback would be appreciated.

One possible use case should probably work right now:

```php
require 'demolibrary.phar';

$demo = new Demo();
$demo->run();
```

We may also want to look into supporting the following use case:

```php
$demo = require 'demolibrary.phar';

$demo->run();
```

For this to work we would need to implement a mechanisms to allow the library author to specify what this should return. Again, #29 might be a good starting point here.

> if multiple libraries are included this way that have overlapping dependency trees

Indeed, and there's probably little we can do about this. IMO it would be sufficient to add some documentation (warnings) and leave this up the consumers of this project.

**Comment by halaei** [comment]
@clue 

> Has anybody already looked into using phar-composer for library projects?

I has! There are programmers who know a little about composer and want to use my package to , let say send SMS with. I thought your package can help.

**Comment by halaei** [comment]
I used you package with a bit of hack to accomplish that. Let say you want to make a phar lib of foo/bar package.
1. Make a local foo/bar-bin project with this composer.json:

    {
      "require": {
        "foo/bar": "*"
      },
      "bin": ["autoload.php"]
    }

2. Make an `autoload.php` file:

    <?php
    require (__DIR__ . '/../vendor/autoload.php');

3. composer install your foo/bar-bin project
4. git clone and composer install clue/phar-composer
5. Find the first line of Herrera\Box\StubGenerator::generate() function:

    public function generate()
    {
        $stub = array($this->shebang, '<?php');
and replace it with:

    public function generate()
    {
        $stub = array('<?php');
 
6. run the build command:

    phar-composer/bin/phar-composer build {path-to foo/bar-bin project}

This gives you a phar file that can be included and used as a library! There may be a simpler process, by the way.

**Comment by RauchF** [comment]
As far as I can tell this will lead to issues when you have more than one .phar built with phar-composer that you want to include, due to classes in the .phar being redeclared (for ex. the class `Extract`).

**Comment by halaei** [comment]
@radford that is true.

**Comment by RauchF** [comment]
I don't know if it's the nicest way, but one possible solution would be to generate the class names at the time the file is compiled, with a suffix unique to each specific `.phar`.

**Comment by helhum** [comment]
If you change the code from 

```php
require 'demolibrary.phar';
```

to 

```php
require 'phar://' . __DIR__ . '/demolibrary.phar/vendor/autoload.php';
```

It works perfectly fine with multiple phar files and with phar files that do not have a script (e.g. libraries)

I use this successfully here:
https://github.com/helhum/typo3_console/blob/master/Classes/Core/ConsoleBootstrap.php#L250

**Comment by helhum** [comment]
@clue Maybe this might be an easy task to [add this](https://github.com/clue/phar-composer/issues/53#issuecomment-224648228) to the documentation. No code changes required.

Oh, and thanks a lot for this project. It helps me a lot easily creating other open source tools :)
