### ISSUE TITLE
Update phpunit 3.7.21

### ISSUE THREAD

**Issue by Amitashree1** [clue/phar-composer#64]
How to update phpunit 3.7.21 to 4.8.* via composer?

**Comment by clue** [comment]
This project is named `phar-composer`, not `composer` :) A first start on how to use composer would be its homepage: https://getcomposer.org/

**Comment by Amitashree1** [comment]
I have already installed composer and my phpunit shows version 3.7.21. Can i update it to 4.8.*?

**Comment by clue** [comment]
Yes: https://phpunit.de/manual/current/en/installation.html

Again, I'm not sure I follow, but your question appears to be unrelated to `phar-composer`.

See also https://github.com/composer/composer#community if you need more help.
