### ISSUE TITLE
Cache - Removed file trying to be loaded

### ISSUE THREAD

**Issue by pelallemant** [clue/phar-composer#70]
Hi,

If you create a class, build the project into a .phar, and then remove the class, there is an error in the 
vendor/composer/ClassLoader.php . 

The removed file is still expected to be present, and I have removed all references to that class.
After a clear of composer and lots of phar-composer build launchs, it finally succeed.

I suspect there is a cache problem about this.

**Comment by clue** [comment]
@pelallemant Thanks for reporting, but I can not currently reproduce the problem you're seeing. This project will not run Composer automatically when building a phar, so it sounds like you might have (had) a problem with your local development instead.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
