### ISSUE TITLE
Problems due to double slash

### ISSUE THREAD

**Issue by Remo** [clue/phar-composer#76]
I tried to package this library https://github.com/kzykhys/Ciconia

Ended with this message:
```
[BadMethodCallException]
  Entry src//Ciconia/Ciconia.php does not exist and cannot be created: phar error: invalid path "src//Ciconia/Ciconia.php" contains double slash
```

It was easy to fix, just had to remove the / after src in composer.json, but maybe it would be nice if this was handled automatically.

**Comment by clue** [comment]
@Remo Good catch, thank you for reporting!

This should be an easy pick, does anybody feel like filing a PR to fix this? :shipit:

**Comment by jyotsna17gupta** [comment]
I have filed the PR: https://github.com/clue/phar-composer/pull/78

**Comment by clue** [comment]
I can not reproduce this and believe this to be obsolete now that #92 is in. We no longer parse any autoload paths and simply bundle everything that's been generated by Composer. Please report back if this problem persists :+1:
